server: 
 port: 8080
 error: 
  include-binding-errors: always
  include-message: always
  
spring:
  
 main:
  allow-circular-references: true # 8 ve 9 yeni eklendi
 jackson: 
  serialization: 
   write-dates-as-timestamps: false
 datasource:
  hikari:
   autoCommit : false
  url: jdbc:postgresql://localhost:5432/JPAMapping
  username: JPAMapping
  password: aylaadem233
  driver-class-name: org.postgresql.Driver
  
 jpa:
  hibernate: 
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
   '[hibernate.format_sql]': true
   


  